<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_CheckboxSeleniumQTPLoadRunner</name>
   <tag></tag>
   <elementGuidId>24d94eb3-8914-42ca-a74d-88462cd8a9a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-1688']/div/div/form/p[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b295e1ba-9b48-4a20-89e8-d3fa2b14b0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Checkbox:SeleniumQTPLoadRunner</value>
      <webElementGuid>e8a6c0a4-dc83-4f91-9ae0-9e254a118871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-1688&quot;)/div[@class=&quot;entry-content-wrap&quot;]/div[@class=&quot;entry-content single-content&quot;]/form[1]/p[4]</value>
      <webElementGuid>0ea35554-b104-4850-9661-34d2c7ecf909</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-1688']/div/div/form/p[4]</value>
      <webElementGuid>77352104-1dc9-4068-af7b-93d312ace4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your comments here…'])[1]/following::p[1]</value>
      <webElementGuid>760af9c8-0ff9-466f-8d0f-a4d04e518858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Text File'])[1]/preceding::p[6]</value>
      <webElementGuid>635991c7-ce5a-4a21-814b-b165a72e0db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Doc File'])[1]/preceding::p[6]</value>
      <webElementGuid>95c43665-06c9-48d2-be60-aca75bab8697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Checkbox:']/parent::*</value>
      <webElementGuid>a03da163-c180-46fb-8d0a-c1133a17e9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]</value>
      <webElementGuid>a3fc7f8e-043b-499f-b259-1fb1ccf7966c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Checkbox:SeleniumQTPLoadRunner' or . = 'Checkbox:SeleniumQTPLoadRunner')]</value>
      <webElementGuid>15e051c1-ec16-472f-b337-7f1214d93344</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
