<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bing</name>
   <tag></tag>
   <elementGuidId>cb6f5b84-779d-4de7-8db5-42a0defbaf15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='link3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#link3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cc702906-399b-42c2-b2cd-4123160e757c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://bing.com</value>
      <webElementGuid>4147c113-729e-43cd-ac5a-fca2313a271f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link3</value>
      <webElementGuid>181c0f2c-d5c3-44a1-9d59-20817966dfb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bing</value>
      <webElementGuid>6ea44d98-5812-471b-8da5-d000e559d8e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link3&quot;)</value>
      <webElementGuid>a6a81f3c-1583-4380-967e-db63931c5f54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='link3']</value>
      <webElementGuid>e7e61b89-d000-4985-8c94-e92bad826b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='page-top']/div/div/div/div/div/div[4]/div/div/a[3]</value>
      <webElementGuid>06204f6d-d850-4135-b641-50a5916bcaab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bing')]</value>
      <webElementGuid>dd113b69-ac47-4fa5-966f-ba8af332275a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[1]/following::a[1]</value>
      <webElementGuid>d3aec4a4-ea36-4737-9309-deb20ca8b6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CherCher Tech'])[1]/following::a[2]</value>
      <webElementGuid>afc06670-e2a5-4838-875e-ef73f63388c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'link3', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>15e6e7f3-fe1b-4eea-824d-f8b8f226691e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bing']/parent::*</value>
      <webElementGuid>2d5732a9-a56d-473e-b4d0-0adc5792ecee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://bing.com')]</value>
      <webElementGuid>2b59081e-549a-43b0-9583-25323efdb656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>5f5ee7a6-1732-4260-9768-5087f685894a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://bing.com' and @id = 'link3' and (text() = 'Bing' or . = 'Bing')]</value>
      <webElementGuid>b256ab86-e32b-4d3a-9eef-8362fa958e6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
