<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Performance TestingManual TestingAgi_d9d729</name>
   <tag></tag>
   <elementGuidId>1d64d722-4aa6-43f6-8b36-e6a4a969debe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='multipleselect[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;multipleselect[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>02efdaba-981d-44e1-afea-2a284a7a6a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>spTextField</value>
      <webElementGuid>2f604db2-0a35-4a7c-a871-7c1a34e6ea22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>multipleselect[]</value>
      <webElementGuid>f3838249-32cc-4f08-9b5d-555a2b915cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9f4305ad-d4fa-47d1-8144-fc7061517f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Performance TestingManual TestingAgile MethodologySelenium</value>
      <webElementGuid>6d6d7ce0-005f-45bb-9d33-7be0bbbd0ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-1688&quot;)/div[@class=&quot;entry-content-wrap&quot;]/div[@class=&quot;entry-content single-content&quot;]/form[1]/p[6]/select[@class=&quot;spTextField&quot;]</value>
      <webElementGuid>bb049403-c627-4c7c-aeb8-90642ec7a1ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='multipleselect[]']</value>
      <webElementGuid>df6df82c-c9cb-4a6e-96ee-667778813698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-1688']/div/div/form/p[6]/select</value>
      <webElementGuid>fd56af8d-7214-4f00-8b74-1c6f58b42dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your comments here…'])[1]/following::select[1]</value>
      <webElementGuid>9cc2ef97-a4ba-4d14-b1f4-e1962ac68e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Text File'])[1]/preceding::select[2]</value>
      <webElementGuid>257ce77d-0927-4ccd-95b4-335db98c09ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Doc File'])[1]/preceding::select[2]</value>
      <webElementGuid>322669fe-cf5e-4fec-b24a-8b808d8ffa68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7a44edf1-d955-4c1d-b703-cb603678bffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'multipleselect[]' and (text() = 'Performance TestingManual TestingAgile MethodologySelenium' or . = 'Performance TestingManual TestingAgile MethodologySelenium')]</value>
      <webElementGuid>c7355313-8525-4bf0-9547-81f1137fb2e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
