<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Practice Alerts_alert</name>
   <tag></tag>
   <elementGuidId>2c766c58-8c95-46e2-a75c-a368fd252072</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='alert']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;alert&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a00dea7e-06e4-4c06-9ca3-eff9ddada92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ed4c70e6-795d-49e8-8d20-9d3ef6ab3128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>9a1b1e94-8120-4a2a-a9c4-c3d5e128d049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Alert</value>
      <webElementGuid>21276db9-d25a-4ab8-973c-f9dc38df63ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>alertbox();</value>
      <webElementGuid>5999d0b0-cfff-4180-9228-ed47b95bb599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-top&quot;)/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;card mb-3&quot;]/div[@class=&quot;col-lg-6&quot;]/input[1]</value>
      <webElementGuid>14423b99-62bd-49cf-8ef8-466358e51ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='alert']</value>
      <webElementGuid>dd678fa3-32b3-43e4-80bc-402144efd696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='page-top']/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>11b01762-29b1-4c0f-ae8f-d7115e5970a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>696f8f84-b09f-4bc9-a73a-43d8952bdfb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'alert']</value>
      <webElementGuid>870f249c-3f34-4bd3-9eae-6a6f5f149147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
