<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Performance TestingManual TestingAgile MethodologySelenium</name>
   <tag></tag>
   <elementGuidId>5895b282-0ab2-4777-9559-65873e90b937</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='multipleselect[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;multipleselect[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d7651f1b-db3c-4a55-ac37-b4373938b20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>spTextField</value>
      <webElementGuid>33f15e84-00c3-4351-91b9-5e556dc5024c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>multipleselect[]</value>
      <webElementGuid>55679d49-aa80-45b0-a775-a536728fa7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>3c55171c-945f-4eb3-a0f7-84882f421625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Performance TestingManual TestingAgile MethodologySelenium</value>
      <webElementGuid>98a7d3f5-f04c-4e59-9343-c7223e1b3128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-1688&quot;)/div[@class=&quot;entry-content-wrap&quot;]/div[@class=&quot;entry-content single-content&quot;]/form[1]/p[6]/select[@class=&quot;spTextField&quot;]</value>
      <webElementGuid>041bd4e7-e20f-4fbe-ada0-7208918e75e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='multipleselect[]']</value>
      <webElementGuid>dd2a0e3d-7283-4b82-a9ec-a678ee4f980a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-1688']/div/div/form/p[6]/select</value>
      <webElementGuid>7187cff7-33d0-4249-8729-864066d581cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your comments here…'])[1]/following::select[1]</value>
      <webElementGuid>db7ca7c6-921b-43c0-ba5a-ef66c0589dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Text File'])[1]/preceding::select[2]</value>
      <webElementGuid>e2a1ccc8-c6cd-4819-a35b-1ddec89d50e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Doc File'])[1]/preceding::select[2]</value>
      <webElementGuid>2d8a27ed-1bbe-4dfc-884a-cad7c6e4b995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f14e96ec-0483-4c31-93a5-ab56aa032b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'multipleselect[]' and (text() = 'Performance TestingManual TestingAgile MethodologySelenium' or . = 'Performance TestingManual TestingAgile MethodologySelenium')]</value>
      <webElementGuid>ed559df9-b2bd-4206-ac8b-b72c66232505</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
