<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your comments here_radioselenium</name>
   <tag></tag>
   <elementGuidId>438163f2-7f0c-42e3-88bb-989eb4cbfb5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='radioselenium']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;radioselenium&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ad35a2f-e08d-4b07-b785-39991acb1700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioselenium</value>
      <webElementGuid>65119f7d-22b0-4733-8fe9-76be3db4ddc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2b36a4f5-da83-4ac3-9c77-759a0ee9cd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>radioselenium</value>
      <webElementGuid>9a87965b-a31b-4385-803b-89a3d399581a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-1688&quot;)/div[@class=&quot;entry-content-wrap&quot;]/div[@class=&quot;entry-content single-content&quot;]/form[1]/p[5]/input[1]</value>
      <webElementGuid>b202a0f9-b767-45de-b967-88020a097d86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='radioselenium']</value>
      <webElementGuid>33044995-cad7-4b9d-bb67-415bc5e4db6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-1688']/div/div/form/p[5]/input</value>
      <webElementGuid>12ccaacd-d137-4254-9cb6-b134393829b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/input</value>
      <webElementGuid>9b5a114e-c420-4800-b80b-88f7f21268f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'radioselenium' and @type = 'radio']</value>
      <webElementGuid>0819dcfa-3bd4-497f-9832-91ec0d9042a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
