<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your comments here_radioloadrunner</name>
   <tag></tag>
   <elementGuidId>4e8590d1-0605-4e6e-933d-39ea8a0e8807</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='radioloadrunner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;radioloadrunner&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d2475ed-9b2e-4d17-857b-2e4f428dd085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioloadrunner</value>
      <webElementGuid>d9ea1e2b-9942-4f18-8eba-16fb9a61a76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>19a2b8be-efd0-4add-aaff-3921a73e456c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>radioloadrunner</value>
      <webElementGuid>e0c00f9b-e235-45c6-92f6-b33a7fe00c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-1688&quot;)/div[@class=&quot;entry-content-wrap&quot;]/div[@class=&quot;entry-content single-content&quot;]/form[1]/p[5]/input[3]</value>
      <webElementGuid>68a54d74-89b0-41e3-9e33-49b3b54df85f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='radioloadrunner']</value>
      <webElementGuid>51e62adc-8506-47ec-84f9-908b57af8671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-1688']/div/div/form/p[5]/input[3]</value>
      <webElementGuid>10b7c829-de2c-4539-afa0-9f04551c14e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/input[3]</value>
      <webElementGuid>f0d52ea0-cff9-4f2f-96a4-55c3259fd57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'radioloadrunner' and @type = 'radio']</value>
      <webElementGuid>67817fe5-4210-447a-ace8-29ef8af49860</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
